### ISSUE TITLE
cf create-service-key does not work

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/capi-k8s-release#101]
The cf `create-service-key` workflow does not exist. The cli returns 500, "An unknown error occurred.".

The server logs make it look like the config key `cc_service_key_client_name` is not present in the `cloud-controller-ng-yaml` config map. Digging a bit further, the `cc_service_key_client_secret` key is also not present (which we believe would be required for this workflow).

The full log message:
```
{
  "timestamp": "2020-11-03T18:16:20.960421254Z",
  "message": "Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"\\\"cc_service_key_client_name\\\" is not a valid config key\", \"error_code\"=>\"CF-InvalidConfigPath\", \"backtrace\"=>[\"/workspace/lib/cloud_controller/config.rb:181:in `invalid_config_path!'\", \"/workspace/lib/cloud_controller/config.rb:125:in `block in valid_config_path?'\", \"/workspace/lib/cloud_controller/config.rb:121:in `each'\", \"/workspace/lib/cloud_controller/config.rb:121:in `valid_config_path?'\", \"/workspace/lib/cloud_controller/config.rb:111:in `get'\", \"/workspace/lib/cloud_controller/dependency_locator.rb:310:in `credhub_client'\", \"/workspace/lib/cloud_controller/dependency_locator.rb:256:in `service_key_credential_object_renderer'\", \"/workspace/lib/cloud_controller/controller_factory.rb:46:in `block in fetch_dependencies'\", \"/workspace/lib/cloud_controller/controller_factory.rb:45:in `map'\", \"/workspace/lib/cloud_controller/controller_factory.rb:45:in `fetch_dependencies'\", \"/workspace/lib/cloud_controller/controller_factory.rb:36:in `dependencies_for_class'\", \"/workspace/lib/cloud_controller/controller_factory.rb:15:in `create_controller'\", \"/workspace/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1635:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1635:in `block in compile!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'\", \"/workspace/middleware/request_logs.rb:38:in `call'\", \"/workspace/middleware/security_context_setter.rb:19:in `call'\", \"/workspace/middleware/vcap_request_id.rb:15:in `call'\", \"/workspace/middleware/cors.rb:49:in `call_app'\", \"/workspace/middleware/cors.rb:14:in `call'\", \"/workspace/middleware/request_metrics.rb:12:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", \"/layers/paketo-buildpacks_bundle-install/gems/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}",
  "log_level": "error",
  "source": "cc.api",
  "data": {
    "request_guid": "159af437-3a09-4a90-b2b7-c65ba4dae0b8::b47a3efd-10f4-40c4-97f5-6674457ad0e7"
  },
  "thread_id": 47124571135600,
  "fiber_id": 47124564557040,
  "process_id": 1,
  "file": "/workspace/lib/sinatra/vcap.rb",
  "lineno": 45,
  "method": "block in registered"
}
```

cc @emmjohnson

**Comment by matt-royal** [comment]
This is likely a regression that was introduced by https://www.pivotaltracker.com/story/show/175080276. I'll make sure we talk about this in our next IPM

**Comment by jamespollard8** [comment]
This came up for us on the cf-for-k8s team as well. All the CATS tests in the services suite are running except the ones using create-service-key - we're seeing this same issue and would love to see a fix when you're able to get to it.

**Comment by tcdowney** [comment]
Jotting down some repro steps for my own future reference...

1. Disable `https` redirection on the `Gateway` in cf-system to more easily support the CATS broker
1. Deployed a test service broker to the env (I used https://github.com/cloudfoundry/cf-acceptance-tests/tree/da0587f5502f80a23b73a756fe932de8bb796c6f/assets/service_broker) using a modified [`setup_new_broker.rb`](https://github.com/cloudfoundry/cf-acceptance-tests/blob/da0587f5502f80a23b73a756fe932de8bb796c6f/assets/service_broker/setup_new_broker.rb) script (updated `cf push` to work with cf7 CLI flags)
1. Viewed the available services with `cf marketplace`
1. Created a service instance (e.g. `cf create-service fake-service-f6b619bc-324a-4165-ac2b-068e0070c1cc fake-plan test-instance`)
1. Attempted to create a service key (e.g. `cf create-service-key test-instance mykey`)
1. Saw the error

```
Creating service key mykey for service instance test-instance as admin...
Unexpected Response
Response code: 500
CC code:       0
CC error code:
Request ID:    53be1058-a4b9-448f-85a2-09245da1c231::03f577af-8323-4340-aaca-6f4125bf21d3
Description:   {
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}
```

**Comment by tcdowney** [comment]
I put out a PR to make these config properties optional (and their usage optional as well).
https://github.com/cloudfoundry/cloud_controller_ng/pull/1984

They were used for CredHub aware service brokers during the binding flow to tell the broker to store the service key's value in a CredHub and give that client access to it. When fetching the service key, Cloud Controller would use the client name/secret to authenticate with CredHub and retrieve it for the user.

`cf-for-k8s` doesn't currently support CredHub so rather than add the properties and have them be unused, I made the usage of the properties themselves optional.

**Comment by jamespollard8** [comment]
Closing now that https://github.com/cloudfoundry/cloud_controller_ng/pull/1984 was merged
