### ISSUE TITLE
Restaging a buildpack app fails

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/capi-k8s-release#25]
Steps to reproduce:

1. Target the CF CLI to a cf-for-k8s deployment
1. `$ cf push catnip`
1. `$ cf restage catnip`

Relevant snippet from a `CF_TRACE=1 cf restage catnip`:

```
Staging app and tracing logs...
REQUEST: [2020-03-24T22:54:42-07:00]
POST /v2/apps/cf328831-b2b6-4f8b-a633-22d0b525a77c/restage HTTP/1.1
...

RESPONSE: [2020-03-24T22:54:42-07:00]
HTTP/1.1 500 Internal Server Error
...
{
  "code": 10001,
  "description": "An unknown error occurred.",
  "error_code": "UnknownError"
}
```

On the API pod, we see this error log:

```
{"error_code"=>"UnknownError", "description"=>"An unknown error occurred.", "code"=>10001, "test_mode_info"=>{"description"=>"images.build.pivotal.io \"9fa6af81-8366-4369-a69d-7f6d0d596688\" already exists", "error_code"=>"CF-HttpError", "backtrace"=>[...]}}
```

Formatted backtrace:

```
[
  "/usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:130:in `rescue in handle_exception'",
  "/usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:120:in `handle_exception'",
  "/usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:381:in `create_entity'",
  "/usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:236:in `block (2 levels) in define_entity_methods'",
  "/cloud_controller_ng/lib/kubernetes/kpack_client.rb:10:in `create_image'",
  "/cloud_controller_ng/lib/cloud_controller/kpack/stager.rb:13:in `stage'",
  "/cloud_controller_ng/app/actions/build_create.rb:77:in `create_and_stage'",
  "/cloud_controller_ng/app/actions/v2/app_stage.rb:23:in `stage'",
  "/cloud_controller_ng/app/controllers/runtime/restages_controller.rb:38:in `restage'",
...
]
```

**Comment by aashah** [comment]
Folks on the team shared some potentially related scenarios -

1) Pushing again...`$ cf push catnip && cf push catnip`
1) Scaling... `$ cf push catnip && cf7 scale catnip -i 2`

**Comment by aashah** [comment]
Hello,

We recently pushed a fix for this in cloud_controller_ng. Should be available in capi-k8s-release -> cf-for-k8s soon.

closing this out.
