### ISSUE TITLE
CF API returns 500 if UAA server certs secret not provided

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/capi-k8s-release#44]
As part of our efforts to eliminate the internal certificate from cf-for-k8s, we tried to deploy without providing a value for the [uaa.serverCerts.secretName](https://github.com/cloudfoundry/capi-k8s-release/blob/60cac48e289421736faf7b34c40f6ce01b675d99/values/_default.yml#L110) property. While everything deployed successfully, we found that we received an error from the `cf create-org` command when running our smoke-tests. The logs from the cf-api-server pod showed this stack trace:
```
Unexpected error while processing request: system lib
        /usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:59:in `add_file'
        /usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:59:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:59:in `block (2 levels) in <class:Store>'
        /usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:245:in `add_trust_ca_to_store'
        /usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:236:in `add_trust_ca'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:127:in `http_client'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:116:in `fetch_uaa_issuer'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:111:in `block in uaa_issuer'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:133:in `with_request_error_handling'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:110:in `uaa_issuer'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:85:in `decode_token_with_key'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:66:in `block in decode_token_with_asymmetric_key'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:65:in `each'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:65:in `decode_token_with_asymmetric_key'
        /cloud_controller_ng/lib/cloud_controller/uaa/uaa_token_decoder.rb:29:in `decode_token'
        /cloud_controller_ng/lib/cloud_controller/security/security_context_configurer.rb:24:in `decode_token'
        /cloud_controller_ng/lib/cloud_controller/security/security_context_configurer.rb:10:in `configure'
        /cloud_controller_ng/middleware/security_context_setter.rb:12:in `call'
        /cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'
        /cloud_controller_ng/middleware/cors.rb:49:in `call_app'
        /cloud_controller_ng/middleware/cors.rb:14:in `call'
        /cloud_controller_ng/middleware/request_metrics.rb:12:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:244:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
        /usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'
```
From what we can tell, it looks like [the UAA server cert is still actually required by the CC code](https://github.com/cloudfoundry/cloud_controller_ng/blob/84c4bd175a70215c89de6ef017db9a233b498176/lib/cloud_controller/uaa/uaa_token_decoder.rb#L122-L129), even though it is optional in the K8s templates. Given that we are already configuring CAPI with a plain-text http URL to talk to UAA, we would like to also remove the need for the internal certificate in the configuration.

Please feel free to reach out if you have any questions.

Regards,
Dave and @acosta11

**Comment by jspawar** [comment]
We are starting work now to make the UAA's certificates optional in CCNG itself. Will be tracking progress on that in this issue

**Comment by jspawar** [comment]
### Tasks
- [ ] Find out where all `uaa.ca_file` config property is used
- [ ] Update `lib/cloud_controller/dependency_locator.rb` to make UAA certs optional
  - `uaa_client` uses it
  - `routing_api_client` uses it
  - `credhub_client` uses it

**Comment by jspawar** [comment]
@davewalter the requisite changes have been made and consuming the latest version of capi-k8s-release should allow you to stop providing a value for the `uaa.serverCerts.secretName` property

**Comment by davewalter** [comment]
Thanks @jspawar!
